services:
  bibliosync:
    build: .
    container_name: bibliosync
    image: bibliosync:latest
    ports:
      - "6080:6080"
    volumes:
      - /volume1/docker/bibliosync/data:/data
      # Acceso a la biblioteca de Calibre (para indexar metadata.db)
      - /volume1/docker/calibreweb:/calibreweb
      # Carpeta para descargas, escaneo y exportación de nuevos libros
      - /volume1/home/Descargas:/descargas
    environment:
      - RESOLUTION=1280x720
    restart: unless-stopped
